@url = http://3.141.45.127:5000/api

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MWQ4MDMzNDdmNjYwNDMxMTBmNWY4Y2MiLCJpYXQiOjE2NDg4MTUxOTEsImV4cCI6MTY0ODkwMTU5MX0.H7eCmwgZf8EDi920yZO9bPQFcOXgZToVHWg1I6EAIhw

## User Registration ##
POST {{url}}/signup
Content-Type: application/json

{
    "firstName" : "john",
    "lastName" : "restivo",
    "email" : "john.restivo@mustdodive.com",
    "mobileNumber" : "0944788338812",
    "password" : "12345678",
    "role": 1,
    "sex": "M"
}

### User Signin Mobile number ###
POST {{url}}/signin
Content-Type: application/json

{
   "email" : "john.restivo@mustdodive.com",
   "password" : "12345678"
}


### User Signin Mobile number ###
POST {{url}}/login/token
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MTQxOTFiNGZkYzhmZTcwZDdlODVlNTYiLCJpYXQiOjE2MzIyMjc1ODUsImV4cCI6MTYzMjMxMzk4NX0.giYic7pR196lUb3xDTthYl_Bo8Kl51UVUem1EpGo2wg

{
   "userId" : "613defb01c718927e053cece",
   "newPassword" : "12345678"
}


### User Signin Mobile number ###
POST {{url}}/admin/add/animal
Content-Type: application/json
Authorization: Bearer {{token}}

{
   "animalsMain" : "lamok"
}





### User Signin Mobile number ###
GET {{url}}/admin/get/query/animal
Authorization: Bearer {{token}}
Content-Type: application/json



### User Signin Mobile number ###
GET {{url}}/admin/get/one/animal?animalId=mainAnimals1641793390122
Authorization: Bearer {{token}}
Content-Type: application/json


### User Signin Mobile number ###
DELETE {{url}}/admin/delete/animal?animalsId=mainAnimals1646715086838
Authorization: Bearer {{token}}
Content-Type: application/json


### User Signin Mobile number ###
PUT {{url}}/admin/update/animal?animalId=mainAnimals1641559408209
Authorization: Bearer {{token}}
Content-Type: application/json


{
   "animalsMain" : "whale"
}


### User Signin Mobile number ###
POST {{url}}/admin/add/sub/animal
Content-Type: application/json
Authorization: Bearer {{token}}

{
   "animalsId" : "mainAnimals1641559408209",
   "subAnimals" : "Pilot Whales"
}


### User Signin Mobile number ###
GET {{url}}/admin/get/query/sub-animal?animalId=mainAnimals1646716175394
Authorization: Bearer {{token}}
Content-Type: application/json



### User Signin Mobile number ###
GET {{url}}/admin/get/one/sub-animal?subAnimalsId=subAnimals164163321649
Authorization: Bearer {{token}}
Content-Type: application/json


### User Signin Mobile number ###

DELETE {{url}}/admin/DELETE/sub-animal?subAnimalsId=subAnimals164163321649
Authorization: Bearer {{token}}
Content-Type: application/json


### User Signin Mobile number ###
PUT {{url}}/admin/update/sub-animal?subAnimalsId=subAnimals1641633216490
Authorization: Bearer {{token}}
Content-Type: application/json


{
       "subAnimals": "maroon",
      "animalsId": "mainAnimals1641559402550"
}



### User Signin Mobile number ###
POST {{url}}/admin/add/location
Content-Type: application/json
Authorization: Bearer {{token}}

{
   "locationName" : "Japan"
}


### User Signin Mobile number ###
GET {{url}}/admin/get/query/location
Authorization: Bearer {{token}}
Content-Type: application/json



### User Signin Mobile number ###
GET {{url}}/admin/get/one/location?locationId=location1641636249249
Authorization: Bearer {{token}}
Content-Type: application/json



### User Signin Mobile number ###
GET {{url}}/admin/get/one/location?locationId=location1641636249249
Authorization: Bearer {{token}}
Content-Type: application/json


### User Signin Mobile number ###
GET {{url}}/admin/delete/location?locationId=location1641636249249
Authorization: Bearer {{token}}
Content-Type: application/json

### User Signin Mobile number ###
PUT {{url}}/admin/update/location?locationId=location1641636249249
Authorization: Bearer {{token}}
Content-Type: application/json


{
   "locationId": "location1641636249249",
   "locationName": "Japan"
}


### User Signin Mobile number ###
POST {{url}}/admin/add/sub/location
Content-Type: application/json
Authorization: Bearer {{token}}

{  
   "locationId": "location1641636249249",
   "subLocationName" : "Sapphoro"
}


### User Signin Mobile number ###
GET {{url}}/admin/get/query/sub-location?locationId=location1641636249249
Authorization: Bearer {{token}}
Content-Type: application/json



### User Signin Mobile number ###
GET {{url}}/admin/get/one/sub-location?subLocationId=subLocation1641637236308
Authorization: Bearer {{token}}
Content-Type: application/json



### User Signin Mobile number ###
PUT {{url}}/admin/update/sub-location?subLocationId=subLocation1641637236308
Authorization: Bearer {{token}}
Content-Type: application/json


{
    "locationId": "location1641636249249",
   "subLocationName" : "Sapporo"
}



### User Signin Mobile number ###
POST {{url}}/admin/add/trips
Content-Type: application/json
Authorization: Bearer {{token}}

{  
   "tripName": "Aichi",
   "month" : "January",
   "year" : 2021
}


### User Signin Mobile number ###
GET {{url}}/admin/get/trips
Authorization: Bearer {{token}}
Content-Type: application/json



### User Signin Mobile number ###
GET {{url}}/admin/get/one/trips?tripId=trips1641638103755
Authorization: Bearer {{token}}
Content-Type: application/json


### User Signin Mobile number ###
GET {{url}}/admin/get/manage/media
Authorization: Bearer {{token}}
Content-Type: application/json



### User Signin Mobile number ###
DELETE {{url}}/admin/delete/manage/media
Authorization: Bearer {{token}}
Content-Type: application/json

### User Signin Mobile number ###
PUT {{url}}/admin/update/trips?tripId=trips1641638103755
Authorization: Bearer {{token}}
Content-Type: application/json


{
 "tripName": "Mexico / Guerrero Negro",
    "month" : "April",
   "year" : 2018
}



### User Signin Mobile number ###
GET {{url}}/public/get/main/animal

### User Signin Mobile number ###
GET {{url}}/public/get/main/location



